-- BetterLife International: live content sync, generated 2026-10-06 13:15 by tools/make_live_sync.php
-- Replaces the site's content tables and updates site settings. Never touches orders, messages, subscribers,
-- admin accounts, passwords or payment keys.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';

-- products (7 rows)
DROP TABLE IF EXISTS `products`;
CREATE TABLE `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(150) NOT NULL,
  `slug` varchar(170) NOT NULL,
  `category` varchar(80) NOT NULL,
  `price` decimal(10,2) DEFAULT NULL,
  `unit` varchar(50) DEFAULT NULL,
  `short_desc` varchar(255) DEFAULT NULL,
  `description` longtext DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `featured` tinyint(1) DEFAULT 0,
  `status` tinyint(1) DEFAULT 1,
  `sort_order` int(11) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `products` (`id`, `name`, `slug`, `category`, `price`, `unit`, `short_desc`, `description`, `image`, `featured`, `status`, `sort_order`, `created_at`, `updated_at`) VALUES
('1', 'BetterLife Honey', 'betterlife-honey', 'Honey', '30000.00', '1 kg jar', 'Sweet, natural honey from BetterLife Agro Tourism Farm.', 'BetterLife Honey is packed by BetterLife Agro Tourism Farm. Like everything from BetterLife Agro Tourism Farm, it is made from what community farmers produce. The farm buys their surplus, adds value and sells it, so every purchase helps keep that market open for refugee, displaced and host-community families.', 'assets/img/product-honey-real.jpg', '1', '1', '1', '2026-09-28 20:26:27', '2026-10-03 15:26:55'),
('2', 'Golden Comb Honey', 'golden-comb-honey', 'Honey', '32000.00', '400g jar', 'Honeycomb harvested whole for the purest, most natural honey experience.', 'For the purist, our Golden Comb Honey is harvested whole from the hive and bottled exactly as nature made it. Chew the comb or let it melt over warm bread. Either way, you are tasting honey the way it was meant to be enjoyed, straight from our apiaries around the BetterLife Farm.', 'assets/img/product-honey-real.jpg', '0', '0', '2', '2026-09-28 20:26:27', '2026-10-04 08:27:59'),
('3', 'BetterLife Ghee', 'betterlife-ghee', 'Ghee', '30000.00', '1 kg jar', 'Organic ghee made from 100% pure cow butter.', 'BetterLife Organic Ghee is made from 100% pure cow butter and is a natural source of energy for cooking. Contains milk. Like everything from BetterLife Agro Tourism Farm, it is made from what community farmers produce. The farm buys their surplus, adds value and sells it, so every purchase helps keep that market open for refugee, displaced and host-community families.', 'assets/img/product-ghee-real.jpg', '1', '1', '2', '2026-09-28 20:26:27', '2026-10-03 15:26:55'),
('4', 'Cultured Butter Ghee', 'cultured-butter-ghee', 'Ghee', '35000.00', '350ml jar', 'A deeper, cultured flavour profile made from fermented cream.', 'Our Cultured Butter Ghee starts with fermented cream for a deeper, tangier flavour before it is slow-clarified into golden ghee. It is a small-batch product made by our farm cooperative, prized by chefs for its aroma and long shelf life without refrigeration.', 'assets/img/product-ghee-real.jpg', '0', '0', '4', '2026-09-28 20:26:27', '2026-10-03 15:13:59'),
('5', 'BetterLife Yoghurt, Vanilla', 'betterlife-yoghurt-vanilla', 'Yoghurt', '7000.00', '1 litre', 'BetterLife Yoghurt in vanilla flavour.', 'BetterLife Yoghurt in vanilla flavour, also available in strawberry. Like everything from BetterLife Agro Tourism Farm, it is made from what community farmers produce. The farm buys their surplus, adds value and sells it, so every purchase helps keep that market open for refugee, displaced and host-community families.', 'assets/img/product-yoghurt-real.jpg', '1', '1', '4', '2026-09-28 20:26:27', '2026-10-03 15:26:55'),
('6', 'BetterLife Yoghurt, Strawberry', 'betterlife-yoghurt-strawberry', 'Yoghurt', '7000.00', '1 litre', 'BetterLife Yoghurt in strawberry flavour.', 'BetterLife Yoghurt in strawberry flavour, also available in vanilla. Like everything from BetterLife Agro Tourism Farm, it is made from what community farmers produce. The farm buys their surplus, adds value and sells it, so every purchase helps keep that market open for refugee, displaced and host-community families.', 'assets/img/product-yoghurt-real.jpg', '1', '1', '3', '2026-09-28 20:26:27', '2026-10-03 15:26:55'),
('7', 'BetterLife Organic Boost', 'betterlife-organic-boost', 'Farm Inputs', '100000.00', '20 litre jerrycan', 'Organic liquid fertilizer that improves soil fertility and boosts crop yield naturally.', 'BetterLife Organic Boost is an eco-friendly, organic liquid fertilizer produced at BetterLife Agro Tourism Farm. Safe for plants, people and the planet, it improves soil fertility and boosts crop yield naturally: the same climate-smart, sustainable approach we teach farmers across our programs, now bottled for your own garden or farm.', 'assets/img/product-organic-boost.jpg', '1', '1', '5', '2026-09-28 20:26:27', '2026-10-04 08:27:59');

-- team_members (20 rows)
DROP TABLE IF EXISTS `team_members`;
CREATE TABLE `team_members` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(150) NOT NULL,
  `role` varchar(150) NOT NULL,
  `category` enum('leadership','staff','board','volunteer') DEFAULT 'staff',
  `bio` text DEFAULT NULL,
  `photo` varchar(255) DEFAULT NULL,
  `email` varchar(150) DEFAULT NULL,
  `facebook` varchar(255) DEFAULT NULL,
  `twitter` varchar(255) DEFAULT NULL,
  `linkedin` varchar(255) DEFAULT NULL,
  `sort_order` int(11) DEFAULT 0,
  `status` tinyint(1) DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `team_members` (`id`, `name`, `role`, `category`, `bio`, `photo`, `email`, `facebook`, `twitter`, `linkedin`, `sort_order`, `status`, `created_at`) VALUES
('1', 'Denise Ayebare', 'Executive Director & Founder', 'leadership', 'Denise Ayebare is a Ugandan lawyer, climate justice advocate and youth leader who founded BetterLife International at nineteen. She currently serves as Secretary for External Affairs of Uganda\'s National Youth Council and has represented young people in regional and international climate-policy processes. Denise previously served as Prime Minister of Uganda\'s Fifth National Youth Parliament and has contributed to youth leadership, climate resilience and locally led development across Africa. Recognised in the Forbes Africa 30 Under 30 Class of 2026, she leads BetterLife\'s work with women, refugees, young people and vulnerable communities, connecting sustainable livelihoods with policy influence and long-term institutional change.', 'assets/img/team/denise-ayebare.jpg', NULL, NULL, NULL, NULL, '1', '1', '2026-09-28 20:26:27'),
('2', 'Samuel Ahabwe', 'Head of Finance', 'leadership', 'Samuel Ahabwe serves as Head of Finance at BetterLife International, supporting the organisation\'s financial planning, accountability and responsible use of resources. He oversees budgeting, expenditure tracking, financial documentation and reporting across BetterLife\'s programmes and country operations. Working closely with the executive and programme teams, Samuel helps ensure that organisational resources are aligned with approved activities and deliver value to the communities BetterLife serves. His role is central to strengthening internal controls, supporting donor compliance and improving the financial systems required for sustainable growth.', 'assets/img/team/ahabwe-samuel.jpg', NULL, NULL, NULL, NULL, '3', '1', '2026-09-28 20:26:27'),
('3', 'Douglas Drake Onen', 'Chief Operations Officer', 'staff', 'Douglas Drake Onen is a legal professional and governance advocate serving as Chief Operations Officer at BetterLife International. Educated at Uganda Christian University, he has gained experience in constitutional governance and legal research, with a particular interest in the rule of law. At BetterLife, Douglas coordinates organisational operations and helps translate institutional strategy into effective programme delivery. He works across country teams to strengthen internal systems, staff coordination, compliance and implementation. His legal background supports BetterLife\'s commitment to accountable governance, responsible partnerships and community-centred development. Douglas brings structured leadership to an organisation operating across different national contexts and serving communities facing displacement, poverty and climate vulnerability.', 'assets/img/team/douglas-drake-onen.jpg', NULL, NULL, NULL, NULL, '7', '1', '2026-09-28 20:26:27'),
('4', 'Shallon Kaitesi', 'Administrator', 'staff', 'Shallon Kaitesi is an environmental advocate and administrator with experience in youth-led climate action and programme coordination. Before joining BetterLife International, her work spanned environmentalism, debate, Rotaract and programme coordination with Cherish Aid Foundation. At BetterLife, Shallon supports the organisation\'s daily administration, internal coordination, documentation and communication across teams. She helps ensure that meetings, records, schedules and operational processes are organised effectively, enabling programme staff to concentrate on community delivery. Her combination of administrative ability and commitment to climate justice strengthens BetterLife\'s youth-led character and its work to build sustainable, inclusive opportunities for vulnerable communities across Africa.', 'assets/img/team/kaitesi-shallon.jpg', NULL, NULL, NULL, NULL, '4', '1', '2026-09-28 20:26:27'),
('5', 'Charity Kembabazi', 'Board Member', 'board', 'Charity Kembabazi is a social scientist, monitoring and evaluation expert, and community development professional serving on the Board of BetterLife International. She brings experience in local government and a practical understanding of how public institutions and community organisations can work together to improve people’s lives.\n\nPreviously serving as a Community Development Officer, Charity worked directly with communities. That experience brings an important perspective to BetterLife’s governance: understanding local priorities, the barriers people face in accessing support, and the relationships needed to sustain community programmes.\n\nHer expertise in monitoring and evaluation complements this background. She brings attention to how programmes are planned, how progress is assessed and how evidence informs decisions. This is particularly relevant to BetterLife’s work connecting training with food production, livelihoods and greater household security.\n\nAs a board member, Charity contributes a combination of community experience, social-science knowledge and an emphasis on accountability. Her background helps inform the organisation’s strategic direction and its commitment to programmes shaped by the people they serve.', 'assets/img/team/kembabazi-charity.jpg', NULL, NULL, NULL, NULL, '20', '1', '2026-09-28 20:26:27'),
('6', 'Comboni Daniel Mutabaazi', 'Country Manager, Tanzania', 'staff', 'Comboni Daniel Mutabaazi serves as BetterLife International\'s Country Manager in Tanzania, leading the organisation\'s national programmes and partnerships. He coordinates community engagement, programme implementation and relationships with local authorities, organisations and other stakeholders. His work helps ensure that BetterLife\'s interventions respond to the realities of the communities in which they are delivered, particularly in sustainable agriculture, climate resilience, youth livelihoods and support for vulnerable households. Daniel also connects the Tanzania team with BetterLife\'s wider regional leadership, strengthening reporting, learning and coordination across countries. His role reflects BetterLife\'s commitment to locally grounded leadership and solutions shaped by the people closest to the challenges being addressed.', 'assets/img/team/comboni-mutabaazi.jpg', NULL, NULL, NULL, NULL, '12', '1', '2026-09-28 20:26:27'),
('7', 'Becky Alec', 'Country Manager, South Sudan', 'staff', 'Becky Alec serves as BetterLife International\'s Country Manager in South Sudan, coordinating programmes that support young people, displaced families and communities affected by economic and climate pressures. She is also active in competitive debate, including international adjudication and South Sudan\'s debate community. This background brings strong communication, analysis and youth-engagement skills to her work. At BetterLife, Becky oversees local implementation, team coordination, stakeholder engagement and programme reporting. She helps ensure that activities are rooted in community priorities while remaining connected to BetterLife\'s regional mission of strengthening livelihoods, resilience, social cohesion and meaningful opportunities for young people across Africa.', 'assets/img/team/alec-becky.jpg', NULL, NULL, NULL, NULL, '10', '1', '2026-09-28 20:26:27'),
('8', 'Victoria Kinobe', 'Country Manager, DR Congo', 'staff', 'Victoria Kinobe Nakatudde is an engineer with experience in water resources, catchment-management planning, environmental and social impact assessment, and stakeholder engagement. Her professional work has included water-resources planning and regulation, alongside participation in regional and international climate discussions. As BetterLife International\'s Country Manager for the Democratic Republic of Congo, Victoria brings technical knowledge of water, environmental management and community engagement to the organisation\'s programmes. She supports locally appropriate interventions addressing climate vulnerability, livelihoods and sustainable resource use. Her experience helps connect technical environmental planning with the everyday needs of communities, strengthening BetterLife\'s ability to design practical, evidence-informed and environmentally responsible programmes.', 'assets/img/team/victoria-kinobe-cop29.jpg', NULL, NULL, NULL, NULL, '11', '1', '2026-09-28 20:26:27'),
('9', 'Ian Agaba', 'Programs Coordinator', 'staff', 'Ian Agaba is a Ugandan lawyer, climate justice advocate, writer and Pan-African youth leader serving as Programmes Coordinator at BetterLife International. His public work includes climate advocacy, youth engagement, public speaking and discussions on climate-related displacement and its effects on children. Ian has also participated in university debate, developing skills in research, policy analysis and persuasive communication. At BetterLife, he supports programme design, implementation, coordination and reporting across the organisation\'s thematic and country teams. He helps connect community experiences with wider conversations about climate justice, livelihoods and youth participation, ensuring that BetterLife\'s programmes remain responsive, practical and grounded in the needs of vulnerable communities.', 'assets/img/team/agaba-ian.jpg', NULL, NULL, NULL, NULL, '8', '1', '2026-09-28 20:26:27'),
('10', 'Desmond Dorvlo', 'Country Manager, Ghana', 'staff', 'Desmond Dorvlo is a Ghanaian communications professional, researcher, writer and debater serving as BetterLife International\'s Country Manager in Ghana. He studied at Kwame Nkrumah University of Science and Technology, where he has worked as a teaching and research assistant in English. His research interests include African literature, political communication, governance, gendered language and public discourse. Desmond has also worked in communications and external relations and produced writing on Ghanaian culture and travel. At BetterLife, he brings together research, storytelling and stakeholder engagement to coordinate programmes, partnerships and community relationships, strengthening the organisation\'s presence and locally led work in Ghana.', 'assets/img/team/desmond-dorvlo.jpg', NULL, NULL, NULL, NULL, '13', '1', '2026-09-28 20:26:27'),
('11', 'Janice Nkajja', 'Head of Communications & Advocacy', 'staff', 'Janice Nkajja is a Ugandan communicator, public speaker and youth advocate serving as Head of Communications and Advocacy at BetterLife International. She was recognised as a co-winner in the speech category of Uganda\'s 2021 National Speech and Debate Championship and has subsequently contributed to debate and youth-communication initiatives. Janice has also served in public-relations work with Signals from the Grassroots. At BetterLife, she leads storytelling, media engagement, advocacy communication and the documentation of community experiences. She helps ensure that the voices of women, refugees, young people and smallholder farmers are represented accurately and with dignity, connecting their realities to partners, policymakers and wider public audiences.', 'assets/img/team/nkajja-janice.jpg', NULL, NULL, NULL, NULL, '6', '1', '2026-09-28 20:26:27'),
('12', 'Desire Ainembabazi', 'Regional Director', 'leadership', 'Desire Ainembabazi is a nutrition and dietetics professional, youth nutrition advocate and Regional Director at BetterLife International. Desire’s work connects food, health and livelihoods, bringing a nutrition perspective to an organisation focused on helping communities grow food and build sustainable sources of income.\n\nPreviously, Desire served as Head of Operations at BetterLife Agro Tourism Farm. This operational background complements expertise in nutrition and dietetics, connecting the practical demands of agricultural work with the importance of nutritious food and household wellbeing.\n\nDesire’s public professional profile highlights advocacy for nutrition, food and wellness, alongside experience in outreach at BetterLife. This combination brings both technical knowledge and community engagement experience to the regional role.\n\nAt BetterLife, Desire contributes a perspective that connects agricultural production with the people it serves. Across farming, livelihoods and school-feeding activities, that perspective helps keep the nutritional value of food central to the organisation’s wider commitment to food security.', 'assets/img/team/desire-ainembabazi.jpg', NULL, NULL, NULL, NULL, '2', '1', '2026-09-28 20:26:27'),
('13', 'Sedrick Otolo', 'Board Member', 'board', 'Sedrick Otolo is a Ugandan technology entrepreneur, author and youth mentor serving on the Board of BetterLife International. His work connects digital innovation, enterprise and community development, with a particular focus on creating opportunities for young people in Northern Uganda.\n\nAs Team Lead at KaKebe Technologies, Sedrick works on technology-driven initiatives that respond to local needs. His technical background includes a diploma in Networking and Cyber Security from ISBAT University, alongside experience in public speaking, coaching and creative writing.\n\nBeyond his technology work, Sedrick engages young people through mentorship and conversations about leadership, character and entrepreneurship. He is a co-founder of The Unlimited Youths and the author of Building Great Character, reflecting his wider interest in helping young people develop their abilities and pursue opportunities.\n\nAt BetterLife, Sedrick brings an entrepreneurial and technology-focused perspective to board discussions. His background is relevant to the organisation’s digital agriculture, youth skills and enterprise work, contributing to its strategic thinking on how practical innovation can support food security and sustainable livelihoods.', 'assets/img/team-sedrick-otolo.webp', NULL, NULL, NULL, NULL, '22', '1', '2026-09-28 20:26:27'),
('14', 'Felicia Davis', 'Board Member', 'board', 'Felicia Davis is a climate justice advocate and sustainability leader with more than two decades of experience connecting environmental action, education and community empowerment. She serves on the Board of BetterLife International, bringing an international perspective on equitable development and the role of communities in shaping climate solutions.\n\nIn 2016, Felicia co-founded the HBCU Green Fund to help finance sustainability projects at Historically Black Colleges and Universities. Her work promotes energy efficiency, renewable energy and sustainable practices while creating opportunities for students and emerging leaders to participate in the climate movement. She also directed the UNCF Building Green Initiative, advancing sustainability at Black, Hispanic-serving and tribal colleges and universities.\n\nFelicia’s commitment to climate justice spans local organising and international engagement. Her environmental career has included work with Ozone Action and Greenpeace, alongside leadership in clean-air advocacy. She was a founding board member of Green 2.0, an organisation working to increase racial diversity in environmental leadership, and has helped connect sustainability advocates across Africa and the diaspora.\n\nIn 2023, the Intentional Endowments Network recognised her with its inaugural Leadership Award for her contributions to climate justice and her support for women and emerging environmental leaders.\n\nAt BetterLife, Felicia’s experience strengthens the board’s perspective on climate resilience, inclusive partnerships and community leadership. Her background aligns closely with the organisation’s commitment to helping women, young people and communities build secure livelihoods and shape their own futures.', 'assets/img/board-felicia-davis.jpg', NULL, NULL, NULL, NULL, '19', '1', '2026-09-28 20:26:27'),
('15', 'Mohamed Nasheed', 'Board Member', 'board', 'In 2008, Nasheed became the first democratically elected president of the Maldives. His administration focused on democratic reforms, human rights and environmental sustainability, and he gained international acclaim for organizing the world\'s first underwater cabinet meeting on climate change.', 'assets/img/board-nasheed.jpg', NULL, NULL, NULL, NULL, '21', '0', '2026-09-28 20:26:27'),
('16', 'Pamela Musimenta', 'Board Member', 'board', 'Pamela Musimenta is a Ugandan water resources engineer, environmentalist and climate justice advocate working with the Ministry of Water and Environment. Her professional interests span water resources planning and regulation, hydraulic engineering, environmental compliance and access to clean, safe water. A UNFCCC advocate and beVisioneers Fellow, Pamela leads community-based work addressing deforestation, land degradation, soil erosion and flood risk through tree nurseries and soil and water conservation. She brings to BetterLife International\'s Board a combination of government experience, technical expertise and grassroots climate leadership, strengthening the organisation\'s work in renewable energy, sustainable agriculture, water security and community resilience across Africa.', 'assets/img/team/pamela-musimenta.jpg', NULL, NULL, NULL, NULL, '21', '1', '2026-09-28 20:26:27'),
('17', 'Bob Natifu', 'Board Member', 'board', 'Bob Natifu is a Ugandan climate-policy practitioner and climate-education advocate serving on the Board of BetterLife International. He is the Acting Commissioner for Climate Change at Uganda’s Ministry of Water and Environment, bringing experience in national climate coordination, public engagement and international cooperation.\n\nHis career has included climate-change outreach and support for Uganda’s National Climate Change Learning Strategy. As a UN CC:Learn Ambassador and Uganda’s focal point for Action for Climate Empowerment, he has helped advance education, training, public awareness and participation as essential parts of the climate response. In 2019, he co-facilitated the seventh Action for Climate Empowerment Dialogue during the Bonn Climate Change Conference.\n\nA professional journalist and graduate of Uganda Christian University, Bob combines policy experience with a background in communication. His interests span climate-risk perceptions, adaptation, governance, climate finance and the role of women in natural-resource management. He has also undertaken international training in climate adaptation and ecosystem-based approaches.\n\nAt BetterLife, this background brings a valuable policy and institutional perspective to the board. His experience is relevant to the organisation’s work connecting food security, sustainable livelihoods and climate resilience, alongside its commitment to community participation and youth learning.', 'assets/img/board-bob-natifu.jpg', NULL, NULL, NULL, NULL, '23', '1', '2026-09-28 20:26:27'),
('18', 'Edwin Namakanga', 'Outreach Coordinator', 'staff', 'Edwin Namakanga is a Ugandan climate justice advocate and demographer with experience in public engagement, youth mobilisation and advocacy on climate displacement. He serves as Outreach Coordinator at BetterLife International, bringing this background to the organisation’s relationships with communities and wider networks.\n\nActive in climate advocacy since 2019, Edwin has organised campaigns and worked with Fridays for Future MAPA and the Rise Up Movement. He founded Refugees for Future Uganda and supports climate migrants through the Ingo Weffe Initiative. His international engagement includes participation in COP26, COP27 and COP28, where he advocated for climate justice and loss-and-damage funding.\n\nAt BetterLife, his outreach role connects the organisation’s practical work with opportunities for participation, collaboration and public understanding. His experience is particularly relevant to programmes involving young people, refugees and communities facing climate pressures, helping connect local concerns with broader conversations about food security, livelihoods and resilience.', 'assets/img/team/edwin-namakanga.jpg', NULL, NULL, NULL, NULL, '9', '1', '2026-10-04 10:00:27'),
('19', 'Alison Linda Ninsiima', 'Monitoring and Evaluation Specialist', 'staff', 'Alison Linda Ninsiima is a Ugandan development practitioner and climate and water advocate with experience in youth programme coordination, stakeholder engagement and community participation. She serves as Monitoring and Evaluation Specialist at BetterLife International, bringing a background that connects practical community work with national and international policy discussions.\n\nHer experience includes youth programme coordination at the Rural Gender and Development Association, where her work has covered programme design and implementation, climate justice, gender equality, digital community development, and water, sanitation and hygiene. She has also worked with the National Water and Sewerage Corporation and contributed to the youth subcommittee organising Uganda Water Week.\n\nAs Focal Point for the Ugandan Youth Parliament for Water, Alison advocates for young people to have a meaningful role in water governance. Her international engagement includes speaking on water finance at the 10th World Water Forum and participating in the Dakar meetings leading towards the 2026 UN Water Conference.\n\nAlison brings this combination of programme experience, community engagement and policy advocacy to BetterLife’s monitoring and evaluation work. Her background offers a valuable perspective on understanding how programmes respond to local needs and how evidence can guide better decisions across food security, livelihoods and climate resilience.', 'assets/img/team/alison-nimusiima.jpg', NULL, NULL, NULL, NULL, '5', '1', '2026-10-04 10:23:06'),
('20', 'Jackson Odida', 'Legal and Compliance Officer', 'staff', 'Jackson Odida is a Ugandan legal professional whose work brings together law, youth leadership and environmental engagement. He serves as Legal and Compliance Officer at BetterLife International, contributing a legal perspective to the organisation’s work with communities and partners.\n\nJackson’s public profile identifies him as the 22nd Guild Speaker of Gulu University and a beVisioneers Fellow. These experiences connect his legal background with student leadership and environmental innovation, bringing a useful combination of institutional engagement and community-focused thinking to BetterLife.\n\nWithin the organisation, his role supports sound governance, clear agreements and responsible programme delivery. His contribution helps strengthen the legal foundations behind BetterLife’s partnerships and operations as its food-security, livelihoods and climate-resilience work grows.', 'assets/img/team/jackson-odida.jpg', NULL, NULL, NULL, NULL, '9', '1', '2026-10-06 10:56:51');

-- stats (8 rows)
DROP TABLE IF EXISTS `stats`;
CREATE TABLE `stats` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `label` varchar(150) NOT NULL,
  `value` varchar(50) NOT NULL,
  `icon` varchar(50) DEFAULT NULL,
  `sort_order` int(11) DEFAULT 0,
  `status` tinyint(1) DEFAULT 1,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `stats` (`id`, `label`, `value`, `icon`, `sort_order`, `status`) VALUES
('1', 'People reached in 2025', '112,430', NULL, '1', '1'),
('2', 'Farmers supported in 2025', '18,900', NULL, '2', '1'),
('3', 'Refugees and host-community members reached in 2025', '41,200', NULL, '3', '1'),
('4', 'Students engaged in climate education', '4,580+', NULL, '4', '1'),
('5', 'Green Libraries and Eco Labs', '20+', NULL, '5', '1'),
('6', 'Household biogas systems', '48+', NULL, '6', '1'),
('7', 'Community boreholes', '65', NULL, '7', '1'),
('8', 'Tree seedlings raised', '50,000+', NULL, '8', '1');

-- programs (5 rows)
DROP TABLE IF EXISTS `programs`;
CREATE TABLE `programs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(150) NOT NULL,
  `slug` varchar(170) NOT NULL,
  `tagline` varchar(255) DEFAULT NULL,
  `summary` text DEFAULT NULL,
  `content` longtext DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `icon` varchar(50) DEFAULT NULL,
  `sort_order` int(11) DEFAULT 0,
  `status` tinyint(1) DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `programs` (`id`, `title`, `slug`, `tagline`, `summary`, `content`, `image`, `icon`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES
('1', 'Climate-Resilient Agriculture and Food Security', 'climate-resilient-agriculture', '', 'We help farmers and families grow food in the face of unreliable rain, poor soils and limited land. The work includes demonstration gardens, composting, mulching, drought-tolerant crops, agroforestry, greenhouse farming, irrigation, poultry, aquaculture and beekeeping.', '', 'assets/img/betterlifeint-source/programs/program-photo-2.jpg', 'leaf', '1', '1', '2026-09-28 20:26:27', '2026-09-28 20:26:27'),
('2', 'RISE: Resilience through Inclusive Skills and Enterprise', 'green-skills-livelihoods', '', 'We train people in skills that respond to local opportunities, then help them move beyond training through savings groups, enterprise support, finance and market connections. Our work spans agriculture, carpentry, tailoring, barbering, poultry, weaving and solar technology.', '', 'assets/img/project-smiles.jpg', 'users', '2', '1', '2026-09-28 20:26:27', '2026-10-06 12:01:08'),
('3', 'Climate Education and Youth Leadership', 'climate-education-youth-leadership', '', 'Through Green Libraries, Eco Labs, school clubs, youth centres, debates, Climate Academies and innovation challenges, children and young people gain the knowledge, tools and confidence to take part in the decisions shaping their future.', '', 'assets/img/betterlifeint-source/programs/program-photo-4.jpg', 'file-text', '3', '1', '2026-09-28 20:26:27', '2026-09-28 20:26:27'),
('4', 'Clean Energy, Water and Restoration', 'clean-energy-water-restoration', '', 'We work with communities on tree nurseries, agroforestry, biogas, briquettes, waste recovery and water access. Each solution is designed to ease pressure on both households and the environment.', '', 'assets/img/betterlifeint-source/programs/program-photo-1.jpg', 'leaf', '4', '1', '2026-09-28 20:26:27', '2026-09-28 20:26:27'),
('5', 'Digital Innovation for Farmers', 'digital-innovation', '', 'Soilla and Agribusiness Connekt bring soil advice, climate information, services, finance and markets closer to farmers. The technology is paired with face-to-face support so that information becomes something people can use.', '', 'assets/img/project-soilla-app.jpg', 'trending-up', '5', '1', '2026-09-28 20:26:27', '2026-09-28 20:26:27');

-- projects (7 rows)
DROP TABLE IF EXISTS `projects`;
CREATE TABLE `projects` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `slug` varchar(220) NOT NULL,
  `category` varchar(150) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `sort_order` int(11) DEFAULT 0,
  `status` tinyint(1) DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `projects` (`id`, `title`, `slug`, `category`, `description`, `image`, `sort_order`, `status`, `created_at`) VALUES
('1', 'Climate Education and Youth Empowerment', 'climate-education-youth-empowerment', 'Climate Education', 'Engaging students in debates, public speaking and Green Libraries that build climate literacy and leadership skills across partner schools.', 'assets/img/project-climate-education.jpg', '1', '1', '2026-09-28 20:26:27'),
('2', 'BetterLife Spring Project', 'betterlife-spring-project', 'Renewable Energy & Agriculture', 'Sustainable Powered Resilient Irrigation for Next Generation Farming (SPRING) — giving South Sudanese farmers access to renewable-energy-powered irrigation so they can grow food despite unpredictable weather.', 'assets/img/project-spring.jpg', '2', '1', '2026-09-28 20:26:27'),
('3', 'RISE', 'rise', 'Empowering Refugees & Host Communities', 'A programme supporting social cohesion and livelihoods between refugee and host communities through shared training, resources and community dialogue.', 'assets/img/project-smiles.jpg', '3', '1', '2026-09-28 20:26:27'),
('4', 'BetterLife Renewable Pathways', 'betterlife-renewable-pathways', 'Plastic Pollution in Uganda', 'Turning plastic waste into fuel and other reusable materials, reducing pollution while creating green income opportunities for youth.', 'assets/img/project-renewable-pathways.jpg', '4', '1', '2026-09-28 20:26:27'),
('5', 'BetterLife Agro-Tourism Farm', 'betterlife-agro-tourism-farm', 'Agriculture in Uganda', 'Our Rukungiri model farm training centre for organic dairy and crop farming — and the source of the honey, ghee and yoghurt sold under the BetterLife Farm brand.', 'assets/img/project-agro-tourism.jpg', '5', '1', '2026-09-28 20:26:27'),
('6', 'Empowering Refugee Women and IDPs Through Smart and Sustainable Agriculture', 'empowering-refugee-women-idps-agriculture', 'Driving Local Solutions for a Global Future', 'Equipping refugee and internally displaced women with climate-smart agricultural skills and small-scale farming techniques to build food security and income.', 'assets/img/project-women-idps.jpg', '6', '1', '2026-09-28 20:26:27'),
('7', 'Soilla App', 'soilla-app', 'AI & IoT Technology', 'A web and mobile platform that leverages AI and IoT technologies to help smallholder farmers monitor soil health and make better-informed farming decisions.', 'assets/img/project-soilla-app.jpg', '7', '1', '2026-09-28 20:26:27');

-- blog_categories (5 rows)
DROP TABLE IF EXISTS `blog_categories`;
CREATE TABLE `blog_categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `slug` varchar(120) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `blog_categories` (`id`, `name`, `slug`) VALUES
('1', 'From the Field', 'from-the-field'),
('2', 'Climate and Food', 'climate-and-food'),
('3', 'Work and Enterprise', 'work-and-enterprise'),
('4', 'Young People and Ideas', 'young-people-and-ideas'),
('5', 'Partnerships and News', 'partnerships-and-news');

-- blog_posts (5 rows)
DROP TABLE IF EXISTS `blog_posts`;
CREATE TABLE `blog_posts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `slug` varchar(220) NOT NULL,
  `category_id` int(11) DEFAULT NULL,
  `excerpt` varchar(500) DEFAULT NULL,
  `content` longtext DEFAULT NULL,
  `featured_image` varchar(255) DEFAULT NULL,
  `author` varchar(100) DEFAULT 'Admin',
  `status` enum('draft','published') DEFAULT 'draft',
  `views` int(11) DEFAULT 0,
  `published_at` datetime DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`),
  KEY `category_id` (`category_id`),
  CONSTRAINT `blog_posts_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `blog_categories` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `blog_posts` (`id`, `title`, `slug`, `category_id`, `excerpt`, `content`, `featured_image`, `author`, `status`, `views`, `published_at`, `created_at`, `updated_at`) VALUES
('1', 'Climate Justice: Beyond Financial Transactions to Protect the Vulnerable', 'climate-justice-beyond-financial-transactions', '2', 'Climate justice is not merely about financial transactions to protect the environment. It embodies the fight for fairness for the communities least responsible for the crisis, yet most affected by it.', '<p>Climate justice is not merely about financial transactions to protect the environment. It embodies the fight for fairness for the communities least responsible for the climate crisis, yet most affected by its consequences.</p><p>Across Uganda, South Sudan, Tanzania, Ghana and the DR Congo, the families BetterLife International works with are on the frontline of a crisis they did little to cause — unpredictable rains, shrinking grazing land, and displacement driven by environmental stress. True climate justice means channelling resources, skills and decision-making power directly to these communities, not just discussing figures in international finance rooms.</p><p>That is why our approach pairs climate education with tangible livelihoods: green skills training, climate-smart agriculture, and renewable energy access such as biogas and boreholes. When a family can irrigate a field with solar power or cook with biogas instead of charcoal, climate justice becomes something they can hold in their hands, not just a policy conversation.</p><p>We continue to advocate for financing that reaches the last mile — the refugee-hosting districts and rural communities that are too often left out of climate finance altogether.</p>', 'assets/img/blog-climate-justice.jpg', 'Admin', 'published', '0', '2024-10-26 09:00:00', '2026-09-28 20:26:27', '2026-09-28 20:26:27'),
('2', 'Climate Change: Amplifying Extreme Weather and Displacement', 'climate-change-extreme-weather-displacement', '2', 'Climate change significantly heightens the risks of extreme weather events — storms, floods, wildfires — and the displacement that follows them.', '<p>Climate change significantly heightens the risks of extreme weather events — such as storms, floods, wildfires, and droughts — and the human displacement that so often follows in their wake.</p><p>In the regions where BetterLife International works, we see this firsthand: families who already fled conflict now facing floods that destroy their new farmland, or droughts that fail the very crops meant to rebuild their food security. Displacement driven by climate stress is compounding an already fragile humanitarian situation across Sub-Saharan Africa.</p><p>Our response combines immediate resilience-building — climate-smart agriculture, water access through boreholes, and renewable energy — with long-term climate education through our Green Libraries and Eco Clubs, reaching thousands of students with the knowledge to adapt and lead.</p><p>Addressing climate-driven displacement requires both humanitarian urgency and sustained investment in local adaptation. It is a challenge we are meeting one community, one borehole, one biogas plant at a time.</p>', 'assets/img/blog-extreme-weather.jpg', 'Admin', 'published', '0', '2024-10-14 09:00:00', '2026-09-28 20:26:27', '2026-09-28 20:26:27'),
('3', 'Congratulations to Dr. Okello Sharon Nagenjwa on Her PhD and Outstanding Community Impact!', 'dr-okello-sharon-nagenjwa-phd', '4', 'We are happy to celebrate the remarkable journey of Dr. Okello Sharon Nagenjwa, who was recently awarded her PhD after years of dedicated research and community impact.', '<p>We are happy to celebrate the remarkable journey of Dr. Okello Sharon Nagenjwa, who was recently awarded her PhD after years of dedicated research and community impact work across Uganda\'s agricultural and refugee-hosting communities.</p><p>Dr. Nagenjwa\'s research has directly informed several of BetterLife International\'s programs in sustainable agriculture and climate-smart farming, helping bridge the gap between academic research and practical, farmer-led solutions.</p><p>Her achievement reflects the spirit of BetterLife International\'s mission: that those closest to a challenge are often best placed to solve it. We congratulate Dr. Nagenjwa and look forward to continued collaboration as we grow our agricultural and livelihoods programs, including the BetterLife Farm.</p>', 'assets/img/blog-sharon-phd.png', 'Admin', 'published', '0', '2024-09-29 09:00:00', '2026-09-28 20:26:27', '2026-09-28 20:26:27'),
('4', 'The Importance of Civic Education in Uganda: An Evaluative Analysis', 'importance-of-civic-education-in-uganda', '4', 'Civic education plays a crucial role in the development of any democratic society, yet in Uganda it remains under-prioritized in many communities.', '<p>Civic education plays a crucial role in the development of any democratic society, yet in Uganda it remains under-prioritized in many communities, particularly among youth and displaced populations.</p><p>Through our Climate Education and Awareness programme, BetterLife International has seen how civic literacy and environmental literacy reinforce one another — young people who understand their rights and responsibilities are also more likely to take an active role in protecting their environment and holding leaders accountable for it.</p><p>We believe civic education should be woven into every level of schooling, not treated as an afterthought. It is one of the quiet foundations of the resilient, self-reliant communities we work to build.</p>', 'assets/img/blog-civic-education.jpg', 'Admin', 'published', '0', '2024-09-20 09:00:00', '2026-09-28 20:26:27', '2026-09-28 20:26:27'),
('5', 'The Naked Truth of Corruption: A Critical Analysis of Uganda\'s Socioeconomic State and Youth-Led Activism', 'naked-truth-of-corruption-uganda', '4', 'Uganda is currently grappling with a critical socio-political issue: rampant corruption, which has become deeply embedded and is fuelling youth-led activism.', '<p>Uganda is currently grappling with a critical socio-political issue: rampant corruption, which has become deeply embedded in public institutions and continues to undermine development outcomes for ordinary citizens.</p><p>At BetterLife International, we see the downstream effects of this every day — resources that should reach vulnerable communities are too often diverted, delayed, or diminished. This is part of why we are youth-led: young people across our five countries of operation are refusing to accept corruption, inequality, or environmental destruction as the status quo.</p><p>Youth-led activism, paired with transparent, community-owned programs like our farm cooperatives and green-skills training, is one practical way to build systems that are accountable from the ground up.</p>', 'assets/img/blog-corruption.jpg', 'Admin', 'published', '0', '2023-09-06 09:00:00', '2026-09-28 20:26:27', '2026-09-28 20:26:27');

-- testimonials (2 rows)
DROP TABLE IF EXISTS `testimonials`;
CREATE TABLE `testimonials` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `quote` text NOT NULL,
  `author_name` varchar(150) NOT NULL,
  `author_role` varchar(150) DEFAULT NULL,
  `photo` varchar(255) DEFAULT NULL,
  `sort_order` int(11) DEFAULT 0,
  `status` tinyint(1) DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `testimonials` (`id`, `quote`, `author_name`, `author_role`, `photo`, `sort_order`, `status`, `created_at`) VALUES
('1', 'The training I received in organic dairy farming changed everything for my family. Today I supply milk for the farm\'s own ghee and yoghurt.', 'A Farmer, Rukungiri Cooperative', 'BetterLife Farm Partner', NULL, '1', '1', '2026-09-28 20:26:27'),
('2', 'Beekeeping gave me an income for the first time since I fled home. Every jar of honey we sell carries our story forward.', 'A Beekeeper', 'Refugee-led Livelihoods Program', NULL, '2', '1', '2026-09-28 20:26:27');

-- impact_stories (3 rows)
DROP TABLE IF EXISTS `impact_stories`;
CREATE TABLE `impact_stories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `caption` varchar(255) DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `sort_order` int(11) DEFAULT 0,
  `status` tinyint(1) DEFAULT 1,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `impact_stories` (`id`, `title`, `caption`, `image`, `sort_order`, `status`) VALUES
('1', 'Empowering Refugee Women', 'Skills training that builds real livelihoods', 'assets/img/impact-story-1.jpg', '1', '1'),
('2', 'Empowering Refugee Communities', 'Resilience built together, family by family', 'assets/img/impact-story-2.jpg', '2', '1'),
('3', 'Building Our Demo Farm', 'How the BetterLife Agro-Tourism Farm began', 'assets/img/impact-story-3.jpg', '3', '1');

-- reports (4 rows)
DROP TABLE IF EXISTS `reports`;
CREATE TABLE `reports` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `year` varchar(10) DEFAULT NULL,
  `file_url` varchar(500) DEFAULT NULL,
  `sort_order` int(11) DEFAULT 0,
  `status` tinyint(1) DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `reports` (`id`, `title`, `year`, `file_url`, `sort_order`, `status`, `created_at`) VALUES
('1', 'BetterLife International Annual Report', '2025', 'assets/reports/betterlife-annual-report-2025.pdf', '1', '1', '2026-10-03 22:40:00'),
('2', 'BetterLife International Annual Report', '2024', 'assets/reports/betterlife-annual-report-2024.pdf', '2', '1', '2026-10-03 22:40:00'),
('3', 'BetterLife International Annual Report', '2023', 'assets/reports/betterlife-annual-report-2023.pdf', '3', '1', '2026-10-03 22:40:00'),
('4', 'BetterLife International Annual Report', '2022', 'assets/reports/betterlife-annual-report-2022.pdf', '4', '1', '2026-10-03 22:40:00');

-- content_items (67 rows)
DROP TABLE IF EXISTS `content_items`;
CREATE TABLE `content_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `page` varchar(40) NOT NULL,
  `section_key` varchar(80) NOT NULL,
  `title` varchar(255) NOT NULL DEFAULT '',
  `subtitle` varchar(255) DEFAULT NULL,
  `body` text DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `cta_label` varchar(120) DEFAULT NULL,
  `cta_href` varchar(255) DEFAULT NULL,
  `extra` varchar(120) DEFAULT NULL,
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `status` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_page_section` (`page`,`section_key`,`sort_order`)
) ENGINE=InnoDB AUTO_INCREMENT=69 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
INSERT INTO `content_items` (`id`, `page`, `section_key`, `title`, `subtitle`, `body`, `image`, `cta_label`, `cta_href`, `extra`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES
('1', 'about', 'how_we_work', 'We Start by Listening', '', 'We work through women’s groups, farmer groups, refugee and host-community structures, schools, community organisations and local facilitators. These groups help us understand what is changing, what has already been tried and what people can realistically sustain.', NULL, NULL, NULL, NULL, '0', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('2', 'about', 'how_we_work', 'People Learn by Seeing and Doing', '', 'A technique explained in a workshop can remain abstract. A garden that is producing through a dry spell is harder to dismiss. We use demonstration sites, local-language facilitation, peer learning and community champions so that people can see, question and test new practices.', NULL, NULL, NULL, NULL, '10', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('3', 'about', 'how_we_work', 'Training Must Lead Somewhere', '', 'Knowledge matters, but so do tools, money and customers. We connect learning to starter inputs, savings, finance, business support, services and markets wherever possible.', NULL, NULL, NULL, NULL, '20', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('4', 'about', 'how_we_work', 'We Build with Existing Groups', '', 'We strengthen existing groups and local institutions instead of creating temporary committees that disappear when a project closes. Local ownership is not an exit strategy added at the end. It is part of the design from the beginning.', NULL, NULL, NULL, NULL, '30', '1', '2026-08-31 16:53:16', '2026-10-02 11:28:55'),
('5', 'about', 'how_we_work', 'We Follow What Changes', '', 'We use monitoring data, participant feedback and field observation to understand whether people are applying what they learnt and whether that application is improving food, income, confidence or resilience.', NULL, NULL, NULL, NULL, '40', '1', '2026-08-31 16:53:16', '2026-10-02 11:28:55'),
('6', 'about', 'who_we_work_with', 'Women and Girls', '', 'Women hold much of the responsibility for food, water and household care, yet often have less access to land, money, technology and decision-making. Our programmes pay attention to the barriers that shape participation, including time, phone access, mobility, confidence and social norms.', NULL, NULL, NULL, NULL, '0', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('7', 'about', 'who_we_work_with', 'Children and Young People', '', 'We work with children and young people through schools, youth centres, climate education, digital learning, livelihoods, leadership and innovation programmes. They are not only preparing for the future; they already have ideas and decisions to contribute today.', NULL, NULL, NULL, NULL, '10', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('8', 'about', 'who_we_work_with', 'Refugees and Displaced Families', '', 'Our programmes support people affected by displacement to rebuild their ability to produce food, earn, save and take part in the local economy. We work with refugees and host communities together whenever possible.', NULL, NULL, NULL, NULL, '20', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('9', 'about', 'who_we_work_with', 'Smallholder Farmers', '', 'We help farmers improve soil and water management, access climate and market information, diversify production and connect to services, finance and buyers.', NULL, NULL, NULL, NULL, '30', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('10', 'about', 'who_we_work_with_gallery', 'Women & girls', '', '', 'assets/img/betterlifeint-source/programs/program-photo-6.jpg', NULL, NULL, 'A woman participating in a BetterLife community programme', '0', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('11', 'about', 'who_we_work_with_gallery', 'Refugees & smallholder farmers', '', '', 'assets/img/project-women-idps.jpg', NULL, NULL, 'A smallholder farmer tending crops', '10', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('12', 'about', 'where_we_work', 'Uganda', '', 'Uganda is where BetterLife began and where much of our work is based. Programmes include climate-resilient agriculture, refugee and host-community livelihoods, women’s economic empowerment, Green Libraries, tree nurseries, clean energy, water access, digital agriculture and BetterLife Agro Tourism Farm. Our West Nile work is coordinated through Yumbe and Bidi Bidi.', NULL, NULL, NULL, NULL, '0', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('13', 'about', 'where_we_work', 'South Sudan', '', 'Through our Juba office and field presence in Yambio, we work on food security, solar-powered irrigation, climate-resilient agriculture and practical livelihoods for young people, women and communities affected by conflict and displacement.', NULL, NULL, NULL, NULL, '10', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('14', 'about', 'where_we_work', 'Tanzania', '', 'Our Tanzania work is based in Kayanga Town, Karagwe District. Together with FADECO, we use schools, community radio and practical training to support climate education, health, green skills and youth enterprise.', NULL, NULL, NULL, NULL, '20', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('15', 'about', 'where_we_work', 'Ghana', '', 'In Ghana, our work focuses on youth leadership, climate action, sustainable livelihoods and community-led environmental solutions.', NULL, NULL, NULL, NULL, '30', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('16', 'about', 'where_we_work', 'Democratic Republic of Congo', '', 'Our work in the Democratic Republic of Congo supports young people and communities affected by poverty, conflict and displacement through livelihoods, environmental action and local participation.', NULL, NULL, NULL, NULL, '40', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('17', 'about', 'where_we_work_gallery', 'Ghana', '', '', 'assets/img/betterlifeint-source/projects/project-climate-education-alt.jpg', NULL, NULL, 'Climate education programme in Ghana', '0', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('18', 'about', 'where_we_work_gallery', 'Uganda', '', '', 'assets/img/betterlifeint-source/programs/program-photo-9.jpg', NULL, NULL, 'Community programme activity in Uganda', '10', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('19', 'about', 'journey', '2021', '', 'BetterLife International was founded in Uganda with USD 200 and a small team of young people.', NULL, NULL, NULL, NULL, '0', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('20', 'about', 'journey', '2022', '', 'The organisation expanded its community programmes and began establishing work in South Sudan and Tanzania.', NULL, NULL, NULL, NULL, '10', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('21', 'about', 'journey', '2023', '', 'BetterLife launched Soilla, expanded its school and environmental work and opened the Apala One Stop Youth Centre in Alebtong.', NULL, NULL, NULL, NULL, '20', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('22', 'about', 'journey', '2024', '', 'We started our communal farms, powered by clean energy. Our water access and livelihoods programmes continued to grow.', NULL, NULL, NULL, NULL, '30', '1', '2026-08-31 16:53:16', '2026-10-02 12:29:41'),
('23', 'about', 'journey', '2025', '', 'BetterLife deepened its work with women in Yumbe through the Foundation S-supported climate-resilience programme and strengthened BetterLife Agro Tourism Farm as a bridge from training to markets.', NULL, NULL, NULL, NULL, '40', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('24', 'about', 'journey', '2026', '', 'We began setting up our 20-acre communal farm, with clean energy supporting its operations. The Women’s Action Circle approach began expanding through Farm Radio International’s Green Leaf Platforms Uganda, and work continued on Soilla, Agribusiness Connekt, the BetterLife Climate Academy and regional youth innovation.', NULL, NULL, NULL, NULL, '50', '1', '2026-08-31 16:53:16', '2026-10-02 12:29:41'),
('25', 'about', 'guides', 'Dignity', '', 'People are partners with knowledge and ability, not passive recipients of help.', NULL, NULL, NULL, NULL, '0', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16');
INSERT INTO `content_items` (`id`, `page`, `section_key`, `title`, `subtitle`, `body`, `image`, `cta_label`, `cta_href`, `extra`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES
('26', 'about', 'guides', 'Community Leadership', '', 'Those living with a problem should have real influence over the response.', NULL, NULL, NULL, NULL, '10', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('27', 'about', 'guides', 'Usefulness', '', 'An idea matters when people can put it to work in their own circumstances.', NULL, NULL, NULL, NULL, '20', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('28', 'about', 'guides', 'Accountability', '', 'We are responsible to the communities, partners and institutions that place their trust in us.', NULL, NULL, NULL, NULL, '30', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('29', 'about', 'guides', 'Inclusion', '', 'Participation must be designed around the barriers people face, not simply offered in theory.', NULL, NULL, NULL, NULL, '40', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('30', 'about', 'guides', 'Learning', '', 'We change course when evidence and experience show us a better way.', NULL, NULL, NULL, NULL, '50', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('31', 'programs', 'climate-resilient-agriculture', 'Women’s Climate Resilience in Yumbe', 'Implemented with support from Foundation S – The Sanofi Collective', 'Before the work began, we spoke with 100 women in Yumbe about the way climate pressure was changing their lives. Many were spending around four hours a day collecting water. Some travelled as far as 24 kilometres in search of firewood. Eighty-one per cent had experienced crop failure, and 63 per cent reported having withdrawn a child from school at some point because the household could not meet the cost.\n\nThose answers changed the shape of the project. This could not be a farming course alone.\n\nBetterLife worked with refugee, displaced and host-community women through local-language training and gardens where they could see each practice working. The women learnt composting, mulching, sack and box gardening, trellising, drought-tolerant crops, agroforestry and briquette-making. They received seedlings and support to use simple digital tools for soil and market information.\n\nAmong the 72 women who completed structured training, knowledge of climate-smart agriculture rose from 22 per cent to 92 per cent. Seventy-two per cent adopted sack or box gardening, 63 per cent took up composting, 54 per cent used mulching and 57 per cent introduced drought-tolerant crops. Participating households reported an average 35 per cent reduction in spending on vegetables as home production improved.\n\nThe figures matter, but so did the way the change happened. Women learnt in groups, saw the methods before risking their own resources and could return with questions after trying them at home. Confidence grew alongside knowledge.', NULL, 'Read the Project Story', 'blog.php', NULL, '0', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('32', 'programs', 'climate-resilient-agriculture', 'Green Leaf Platforms Uganda', 'In partnership with Farm Radio International', 'What happens after a radio programme ends?\n\nA woman may hear about a regenerative farming practice and understand it perfectly, yet still be unable to try it. She may not control the land, own a phone or have the materials to risk on an unfamiliar method. She may need to see the practice working nearby before she trusts it with a small harvest.\n\nBetterLife’s partnership with Farm Radio International is designed around that gap between receiving information and acting on it.\n\nUnder Green Leaf Platforms Uganda, radio and digital agricultural content is connected to Women’s Action Circles across 12 districts. These circles build on groups women already trust, including savings groups, farmer organisations, cooperatives and community networks.\n\nWomen listen, discuss what the information means in their setting, ask questions, visit demonstration plots and test practices together. Peer champions support those with limited access to phones or extension services. Women’s feedback also travels back into the programme, helping shape content around the questions and barriers they are actually facing.\n\nFarm Radio International brings its radio, digital and farmer-learning experience. BetterLife leads the women’s inclusion work on the ground, connecting listening to learning, practice and adoption.\n\nThe model grows from a lesson we first saw clearly in Yumbe: women adopt what they can see, and groups often carry change farther than individuals working alone.', NULL, 'Learn About Green Leaf Platforms', 'blog.php', NULL, '10', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('33', 'programs', 'climate-resilient-agriculture', 'BetterLife SPRING', 'Sustainable Powered Resilient Irrigation for Next Generation Farming', 'In South Sudan, farming families are expected to plan around rainfall that is becoming harder to predict. When rain stops too early, households lose food and the income they hoped to earn from the season.\n\nBetterLife SPRING combines solar-powered irrigation with practical training in soil health, crop planning and water management. Farmers, refugees and displaced families can produce more reliably through dry periods without depending on fuel-powered pumping.\n\nThe project brings together clean energy, food production and livelihoods. The aim is not simply to install irrigation equipment, but to help communities use it well, maintain it and turn more reliable production into stronger household security.', NULL, 'Explore BetterLife SPRING', 'blog.php', NULL, '20', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('34', 'programs', 'climate-resilient-agriculture', 'BetterLife Agro Tourism Farm', '', 'The farm is BetterLife’s working demonstration and market link. Farmers learn through solar-powered irrigation, greenhouse farming, beekeeping, dairy production and livestock rearing, then have a route to supply produce through BetterLife Agro Tourism Farm Ltd.', NULL, 'Discover the Farm', 'farm.php', NULL, '30', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('35', 'programs', 'green-skills-livelihoods', 'RISE', 'Market Inclusive Livelihood Pathways to Self-Reliance', 'RISE brings refugees and host-community members into the same training groups and local economy.\n\nParticipants learn practical skills such as poultry, farming, carpentry, tailoring, barbering and solar technology. They then receive mentorship, business support, market connections and access to small loans. Where appropriate, BetterLife helps participants who lack conventional collateral by acting as a guarantor.\n\nThe economic work also creates room for social cohesion. Refugees and host-community members build relationships as they train, save, trade and solve business problems together. Peacebuilding becomes part of ordinary economic life rather than a separate conversation in a workshop.\n\nAcross target groups, 78 per cent of participants moved into sustainable income pathways, 85 per cent reported improved refugee-host relations and food insecurity fell by 40 per cent.', NULL, 'Explore RISE', 'blog.php', NULL, '0', '1', '2026-08-31 16:53:16', '2026-10-06 12:01:41'),
('36', 'programs', 'green-skills-livelihoods', 'Agribusiness Connekt', '', 'Farmers are often trained to produce and then left alone at the point where business begins.\n\nAgribusiness Connekt links farmers and small agricultural enterprises to buyers, finance, services and market information. It helps producers understand what customers need, find opportunities beyond their immediate location and make better decisions about when and where to sell.\n\nThe platform also supports farmers trained through BetterLife programmes, giving them a route from production into longer-term enterprise.', NULL, 'Explore Agribusiness Connekt', 'blog.php', NULL, '10', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('37', 'programs', 'climate-education-youth-leadership', 'Green Libraries, Eco Labs and School Climate Clubs', '', 'Green Libraries and Eco Labs give learners access to books, digital resources and practical environmental activities. Students take part in school gardens, tree planting, waste separation, plastic banks, debates and public speaking.\n\nMore than 4,500 students have been engaged through school climate education, and BetterLife has supported over 20 Green Libraries and Eco Labs. Our school work has included Lake Victoria School Entebbe and Buddo Junior School.\n\nThe aim is not to turn every child into a climate expert. It is to make the subject understandable enough for them to connect it to their home, school and community, and confident enough for them to act.', NULL, 'Explore Green Libraries', 'blog.php', NULL, '0', '1', '2026-08-31 16:53:16', '2026-08-31 16:53:16'),
('38', 'programs', 'climate-education-youth-leadership', 'Apala One Stop Youth Centre', '', 'Talent exists in rural communities. Access often does not.\n\nThe Apala One Stop Youth Centre in Alebtong gives young people a place to read, use computers, learn digital skills and develop ideas. Launched in December 2023, the centre opened with ten computers, more than 3,000 books and space to serve around 400 young people.\n\nWe worked on the centre alongside COMESA, which supported its establishment with the Apala youth and community as part of its Silencing the Guns campaign, together with Save the Children, the Horn of Africa Youth Network, Epuka Ugaidi and Uganda’s National Youth Council. Before the launch on 21 December 2023, twenty young people were trained to manage the hub, alongside training in conflict prevention and peacebuilding.\n\nApala is a place for peacebuilding as well as learning. In a part of Northern Uganda still living with the legacy of conflict, it gives young people from different backgrounds a shared place to build skills, find mentors and lead.\n\nApala is both a learning centre and a statement about opportunity: where a young person is born should not decide how far their curiosity can take them.', NULL, 'Visit the Apala Story', 'blog.php', NULL, '10', '1', '2026-08-31 16:53:16', '2026-10-06 12:00:27'),
('39', 'programs', 'climate-education-youth-leadership', 'Climate Education and Youth Enterprise in Tanzania', '', 'Together with FADECO, BetterLife uses schools, community radio and practical training to reach young people and communities in Tanzania.\n\nFADECO, the Family Alliance for Development and Cooperation, has worked in Karagwe since 1993, across agriculture, environment, technology and community media. Its station, FADECO Radio on 100.8 FM, carries information on climate, agriculture, health and livelihoods into communities that formal training may not reach.\n\nBetterLife is a partner in Empowering Communities Through Climate Action, a FADECO project supported by AllPeopleBeHappy, contributing training tools and expertise in climate-smart agriculture and enterprise development. By July 2025 the project had trained more than 25 young entrepreneurs in climate-smart and green business and 30 community members in conservation tillage and agroforestry, planted more than 8,000 trees and reached more than 30,000 people through FADECO Radio.\n\nIn schools, climate clubs at Karadea Primary, Bohari Primary and Karagwe Secondary involve students in tree planting, waste management and environmental leadership.\n\nYoung people also learn skills such as reusable sanitary-pad production and liquid soap-making. The activities respond to health and dignity while opening small routes into enterprise.', NULL, 'Explore Our Work in Tanzania', 'blog.php', NULL, '20', '1', '2026-08-31 16:53:16', '2026-10-06 12:00:27'),
('40', 'programs', 'climate-education-youth-leadership', 'BetterLife Climate Leadership Academy', '', 'Climate negotiations can feel distant from the places already living with the consequences. The BetterLife Climate Leadership Academy helps young Africans understand those negotiations and connect them to what is happening in their own communities.\n\nParticipants learn about adaptation, climate finance, loss and damage, negotiations and advocacy. The academy also asks a more grounded question: what do these decisions mean for a farmer facing drought, a family displaced by floods or a young person trying to build a future?\n\nSupported by Moonshot, the virtual academy brings together young people from Uganda and across Africa to learn from experts and one another.', NULL, 'Explore the Climate Academy', 'blog.php', NULL, '30', '1', '2026-08-31 16:53:16', '2026-10-06 12:00:27'),
('41', 'programs', 'climate-education-youth-leadership', 'Climate Innovation Hackathons', '', 'BetterLife’s hackathon work gives young people a real problem, a team and room to build. Participants use technology, entrepreneurship and local knowledge to develop practical responses to climate and community challenges.\n\nWe work with KaKebe Technologies, a youth-led tech company in Lira City, on climate innovation hackathons and the Kakebe Tech Camp. BetterLife was among the partners that made Camp 2025 possible: a two-week residential camp at Jerusalem Heritage School in Lira, from 5 to 19 January 2025, which trained 257 young people from across East Africa.\n\nAlongside robotics, artificial intelligence, software development and entrepreneurship, the camp’s curriculum included Climate Action and Eco Action, using technology to promote sustainability, renewable energy, waste management and climate awareness. Every track ended with a working prototype, among them Natural Life, a website that educates and mobilises people towards sustainable choices.\n\nThe camp’s other partners and supporters included Huawei Technologies, Lira University, Jerusalem Heritage School, The Unlimited Youths, Lira City Council and Sky Water.', NULL, 'Explore Youth Innovation', 'blog.php', NULL, '40', '1', '2026-08-31 16:53:16', '2026-10-06 12:21:15'),
('42', 'programs', 'clean-energy-water-restoration', 'Community Tree Nurseries and Agroforestry', '', 'BetterLife-supported nurseries have raised more than 50,000 indigenous and fruit-tree seedlings, with over 20,000 distributed to schools, farmers and communities.\n\nFruit trees can contribute to nutrition and income. Indigenous trees protect soil, provide shade and support biodiversity. Through agroforestry, trees become part of the farm rather than competing with it.\n\nWe focus on what happens after distribution, including care, monitoring and survival. A seedling in the ground is a beginning, not a result by itself.', NULL, 'Explore Nature Restoration', 'blog.php', NULL, '0', '1', '2026-08-31 16:53:17', '2026-08-31 16:53:17'),
('43', 'programs', 'clean-energy-water-restoration', 'Clean Cooking and Biogas', '', 'Through BetterLife Renewable Pathways, we work on clean cooking in schools and refugee communities. Our biogas work is part of it.\n\nBetterLife has supported more than 48 household biogas systems. Families turn organic waste into cleaner cooking energy, reducing smoke inside the home and dependence on firewood and charcoal.\n\nThe process also produces an organic by-product that can be returned to the soil. One household system therefore connects waste, energy, health and farming.', NULL, 'Explore Clean Energy', 'blog.php', NULL, '10', '1', '2026-08-31 16:53:17', '2026-10-06 13:14:10'),
('44', 'programs', 'clean-energy-water-restoration', 'Water Access', '', 'BetterLife has supported 65 community boreholes. Reliable water reduces the time and distance people travel, improves household health and makes small-scale food production more possible.\n\nFor us, water is not a side issue. It sits at the centre of health, food, education and climate resilience.', NULL, NULL, NULL, NULL, '20', '1', '2026-08-31 16:53:17', '2026-08-31 16:53:17'),
('45', 'programs', 'clean-energy-water-restoration', 'BetterLife Renewable Pathways', '', 'Alongside clean cooking, we work with schools and communities on waste separation, plastic banks, recycling and the responsible reuse of materials. Four school plastic banks give learners a practical way to understand waste and participate in keeping plastics out of the environment.\n\nThe programme also explores safe, locally appropriate ways of recovering value from materials that would otherwise be dumped or burnt.', NULL, 'Explore Renewable Pathways', 'blog.php', NULL, '30', '1', '2026-08-31 16:53:17', '2026-10-06 13:14:46'),
('46', 'programs', 'clean-energy-water-restoration', 'Briquette-Making', '', 'Women and vulnerable households learn to make briquettes from suitable agricultural and organic waste. Briquettes can reduce dependence on firewood and charcoal while creating a product for household use or small-scale sale.\n\nFor a woman who spends hours collecting fuel, an alternative made closer to home can mean saved time as well as income.', NULL, NULL, NULL, NULL, '40', '1', '2026-08-31 16:53:17', '2026-08-31 16:53:17'),
('47', 'programs', 'digital-innovation', 'Soilla', '', 'Soilla is BetterLife’s digital agricultural advisory platform. It helps farmers access soil and crop guidance, climate information, market prices and agricultural services.\n\nFarmers can use the platform to better understand what may grow in their soil, monitor farm conditions, locate suppliers and experts and connect with other producers. The aim is to make information that is often expensive or distant more accessible to smallholder farmers.\n\nSoilla is paired with field training because owning a phone or receiving data does not automatically make a tool useful. Farmers need confidence, local support and information that fits their crops and circumstances.\n\nOur engagement with the World Food Programme has contributed to work around farmer information, verification and the responsible use of agricultural and climate data.', NULL, 'Explore Soilla', 'blog.php', NULL, '0', '1', '2026-08-31 16:53:17', '2026-08-31 16:53:17'),
('48', 'programs', 'digital-innovation', 'Agribusiness Connekt', '', 'Where Soilla supports production decisions, Agribusiness Connekt focuses on the business around the farm. It links producers to buyers, finance, services and market opportunities.\n\nTogether, the two platforms respond to a gap we see repeatedly: farmers learn how to produce, but remain disconnected from the systems that determine whether production becomes income.', NULL, 'Explore Agribusiness Connekt', 'blog.php', NULL, '10', '1', '2026-08-31 16:53:17', '2026-08-31 16:53:17'),
('49', 'programs', 'our-projects', 'Dovetail Impact Foundation', 'Growing without losing what made the work local', 'As BetterLife expanded, we had to answer a difficult question: how do we reach more people without becoming distant from the communities that shaped us?\n\nDovetail Impact Foundation has supported BetterLife through strategic acceleration and institutional strengthening. The relationship has helped us clarify our theory of change, strengthen how we measure and communicate impact and build more deliberate systems for growth and resource mobilisation.\n\nThis support sits behind all our programmes rather than inside one field project. It helps us examine the full path from training to application, from application to income and from individual progress to stronger community systems.\n\nGrowth, for BetterLife, is not simply a larger number. It is the ability to reach more people while protecting the dignity, usefulness and local ownership of the work.', NULL, NULL, NULL, NULL, '0', '1', '2026-08-31 16:53:17', '2026-08-31 16:53:17'),
('50', 'farm', 'on_the_farm', 'Solar-Powered Irrigation', '', 'Water is pumped and distributed using solar energy, helping crops survive when rainfall is unreliable.', NULL, NULL, NULL, NULL, '0', '1', '2026-08-31 16:53:17', '2026-08-31 16:53:17');
INSERT INTO `content_items` (`id`, `page`, `section_key`, `title`, `subtitle`, `body`, `image`, `cta_label`, `cta_href`, `extra`, `sort_order`, `status`, `created_at`, `updated_at`) VALUES
('51', 'farm', 'on_the_farm', 'Greenhouse and Crop Farming', '', 'Farmers learn water-efficient production, soil management, crop care and methods suited to limited land.', NULL, NULL, NULL, NULL, '10', '1', '2026-08-31 16:53:17', '2026-08-31 16:53:17'),
('52', 'farm', 'on_the_farm', 'Dairy and Livestock', '', 'Livestock supports food, manure, household income and the farm’s dairy value chain.', NULL, NULL, NULL, NULL, '20', '1', '2026-08-31 16:53:17', '2026-08-31 16:53:17'),
('53', 'farm', 'on_the_farm', 'Beekeeping', '', 'Community beekeeping creates income while encouraging the protection of trees and flowering plants.', NULL, NULL, NULL, NULL, '30', '1', '2026-08-31 16:53:17', '2026-08-31 16:53:17'),
('54', 'farm', 'on_the_farm', 'Poultry and Aquaculture', '', 'Diversified production reduces the risk of depending on one crop or one season.', NULL, NULL, NULL, NULL, '40', '1', '2026-08-31 16:53:17', '2026-08-31 16:53:17'),
('55', 'farm', 'on_the_farm', 'Seedlings', '', 'Participants receive free seedlings to establish gardens of their own and begin moving towards independent production.', NULL, NULL, NULL, NULL, '50', '1', '2026-08-31 16:53:17', '2026-08-31 16:53:17'),
('56', 'products', 'farm_gallery', 'Refugees training on the farm', '', '', 'assets/img/betterlifeint-source/programs/program-photo-1.jpg', NULL, NULL, NULL, '0', '1', '2026-08-31 16:53:17', '2026-08-31 16:53:17'),
('58', 'home', 'hero_gallery', 'Building a greenhouse with women in Yumbe', NULL, NULL, 'assets/img/yumbe-greenhouse-group.webp', NULL, NULL, NULL, '0', '1', '2026-09-28 15:34:30', '2026-09-28 15:34:30'),
('59', 'home', 'hero_gallery', 'BetterLife Agro Tourism Farm from above', NULL, NULL, 'assets/img/farm-aerial-view-1.webp', NULL, NULL, NULL, '10', '1', '2026-09-28 15:34:30', '2026-09-28 15:34:30'),
('60', 'home', 'hero_gallery', 'Winnowing grain after harvest', NULL, NULL, 'assets/img/woman-winnowing-grain.webp', NULL, NULL, NULL, '20', '1', '2026-09-28 15:34:30', '2026-09-28 15:34:30'),
('61', 'home', 'hero_gallery', 'RISE participants training together', NULL, NULL, 'assets/img/smiles-group-under-tree-2.webp', NULL, NULL, NULL, '30', '1', '2026-09-28 15:34:30', '2026-10-06 12:00:27'),
('62', 'home', 'hero_gallery', 'Children in a West Nile community', NULL, NULL, 'assets/img/village-children-portrait.webp', NULL, NULL, NULL, '40', '1', '2026-09-28 15:34:30', '2026-09-28 15:34:30'),
('63', 'home', 'hero_gallery', 'Solar power reaching a rural community', NULL, NULL, 'assets/img/solar-panel-installation-2.webp', NULL, NULL, NULL, '50', '1', '2026-09-28 15:34:30', '2026-09-28 15:34:30'),
('64', 'home', 'hero_gallery', 'A school climate club in session', NULL, NULL, 'assets/img/classroom-climate-club.webp', NULL, NULL, NULL, '60', '1', '2026-09-28 15:34:30', '2026-09-28 15:34:30'),
('65', 'home', 'hero_gallery', 'A market stall run by a BetterLife entrepreneur', NULL, NULL, 'assets/img/market-stall-vendor.webp', NULL, NULL, NULL, '70', '1', '2026-09-28 15:34:30', '2026-09-28 15:34:30'),
('66', 'home', 'hero_gallery', 'Two generations working the same field', NULL, NULL, 'assets/img/farmers-planting-together.webp', NULL, NULL, NULL, '80', '1', '2026-09-28 15:34:30', '2026-09-28 15:34:30'),
('67', 'home', 'hero_gallery', 'The BetterLife field team on assignment', NULL, NULL, 'assets/img/field-team-group-under-tree.webp', NULL, NULL, NULL, '90', '1', '2026-09-28 15:34:30', '2026-09-28 15:34:30'),
('68', 'programs', 'climate-education-youth-leadership', 'Opening the Way for the Next Generation', NULL, 'When BetterLife International’s founder, Denise Ayebare, won the Moonshot Borderless Award, she wanted to turn that recognition into an opportunity for other young people.\n\nHaving begun her own leadership journey as a teenager and founded BetterLife at nineteen, Denise understood how much young people can achieve when someone takes their ideas seriously. She also recognised the barriers facing emerging climate leaders: limited access to mentorship, learning opportunities and the spaces where decisions about their future are made.\n\nShe wanted to extend her leadership by helping others develop theirs. That ambition helped shape the vision for the BetterLife Climate Leadership Academy: a place where young people could deepen their understanding of climate change, develop their ideas and build the confidence to lead.\n\nThe vision connects climate knowledge with the realities young people see around them, from failed harvests and food insecurity to displacement and limited livelihood opportunities. It makes room for young leaders whose experience begins in a farming community, a refugee settlement, a school or a neighbourhood, and whose ideas deserve the opportunity to grow.\n\nFor Denise, the next chapter of leadership is about opening that opportunity to others. Through the Academy, she wants to nurture a generation of young climate leaders equipped to organise, influence decisions and develop solutions alongside their communities.', NULL, NULL, NULL, NULL, '35', '1', '2026-10-06 12:41:53', '2026-10-06 12:41:53');

-- Site settings (content only)
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('about_image', 'assets/img/about-real-1.jpg') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('about_who_text', 'Denise Ayebare founded BetterLife International in Uganda in 2021. She was nineteen, and the organisation began with USD 200 and a small group of young people who were tired of watching communities receive short-term help while the conditions keeping them vulnerable remained unchanged.\n\nThey had seen farmers lose a season and start again with nothing. They had seen women carry the weight of food, water and household survival without access to finance or decision-making. They had seen young people complete training and still have no tools, customers or way into work. They had also seen how much knowledge already existed inside communities, often overlooked by programmes designed from far away.\n\nBetterLife was created to work differently.\n\nWhat began as a small youth-led initiative in Uganda now works across Uganda, South Sudan, Tanzania, Ghana and the Democratic Republic of Congo. The organisation brings together climate-resilient agriculture, livelihoods, clean energy, water, restoration, education, technology and market access.\n\nThe work has grown, but the starting point has remained the same: people closest to a problem must have a real hand in defining it, designing the response and deciding what success looks like.') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('about_who_title', 'Who We Are') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('address', 'Rukungiri, Uganda') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('board_quote', 'BetterLife International is changing lives at every level, empowering youth, building resilient communities, and inspiring hope where it\'s needed most.') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('board_quote_author', 'BetterLife International Board of Directors') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('email', 'info@betterlifeint.org') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('facebook', 'https://facebook.com/betterlifeintl') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('farm_image', 'assets/img/farm-field-1.jpg') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('farm_tagline', 'From immediate support to lasting independence') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('farm_text', 'BetterLife Agro Tourism Farm is a clean-energy-powered social enterprise where our humanitarian support, climate-smart agriculture and market-access work come together. Solar energy powers the farm\'s irrigation, water pumping and key production activities, reducing dependence on fossil fuels while demonstrating that agriculture can be both productive and environmentally responsible.\n\nThe farm supports refugees, women and vulnerable households to move from emergency assistance towards producing their own food and earning stable incomes. Refugees who are able to participate contribute up to two hours of their time at the farm while rebuilding their livelihoods. In return, they receive practical agricultural training, food support, free seedlings and other starter inputs to establish gardens of their own. This flexible, temporary arrangement allows participants to contribute with dignity while retaining time to care for their families, study, seek employment or develop other sources of income. As they become stable, they can transition into independent producers and suppliers to BetterLife.\n\nThe farm demonstrates solar-powered irrigation, greenhouse farming, beekeeping, livestock rearing and sustainable food production. Produce from the farm and farmers trained by BetterLife International is processed and marketed through BetterLife Agro Tourism Farm Ltd as products such as BetterLife Honey, Ghee and Yoghurt in Strawberry and Vanilla, connecting training and production to packaging, customers and real household income.\n\nIt also serves as a practical learning and agro-tourism space where schools, farmers, partners and visitors can experience how clean energy, agriculture and local enterprise can work together to address hunger, unemployment and climate vulnerability.') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('farm_title', 'BetterLife Agro Tourism Farm') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('favicon', 'assets/img/favicon.png') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('footer_about', 'BetterLife International works with communities across five African countries to build food security, livelihoods and practical climate resilience.') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('founded_year', '2021') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('hero_image', 'assets/img/hero-real-1.jpg') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('hero_image_1', 'assets/img/hero-real-1.jpg') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('hero_image_10', 'assets/img/betterlifeint-source/programs/program-photo-3.jpg') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('hero_image_11', 'assets/img/betterlifeint-source/projects/project-agro-tourism-alt.jpeg') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('hero_image_12', 'assets/img/betterlifeint-source/impact-reports/impact-photo-1.jpeg') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('hero_image_2', 'assets/img/farm-field-1.jpg') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('hero_image_3', 'assets/img/product-honey.jpg') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('hero_image_4', 'assets/img/about-real-1.jpg') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('hero_image_5', 'assets/img/farm-field-2.jpg') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('hero_image_6', 'assets/img/program-trees.jpg') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('hero_image_7', 'assets/img/product-ghee.jpg') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('hero_image_8', 'assets/img/product-yogurt.jpg') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('hero_image_9', 'assets/img/betterlifeint-source/programs/program-photo-1.jpg') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('hero_kicker', 'Founded in Uganda. Working across five African countries.') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('hero_subtitle', 'BetterLife works with women, young people, refugees, displaced families and farming communities to turn climate pressure into practical action: food people can grow, skills they can earn from, cleaner energy and stronger routes to market.') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('hero_title', 'Led by people who understand what it means to begin again.') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('instagram', 'https://instagram.com/betterlifeintl') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('linkedin', 'https://linkedin.com/company/betterlifeintl') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('logo', 'assets/img/logo.png') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('mission_text', 'To create a better life for everyone by promoting sustainable practices, empowering young people, supporting vulnerable groups, and fostering peace and equality in communities.') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('phone', '+256 770 933 286') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('shop_email', 'farm@betterlifeint.org') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('site_name', 'BetterLife International') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('tagline', 'Building Hope') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('twitter', 'https://twitter.com/betterlifeintl') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('usd_rate', '3950') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('vision_text', 'We envision a world where every person, regardless of their background, has the opportunity to live a fulfilling and sustainable life.') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES ('youtube', 'https://youtube.com/@betterlifeintl') ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`);

SET FOREIGN_KEY_CHECKS = 1;
